// Accessing the head: O(1)
// Accessing the tail: O(n)
// Accessing a middle node: O(n)
// Inserting / Removing the head: O(1)
// Inserting / Removing the tail: O(n) to access + O(1)
// Inserting / Remove the middle node: O(n) to access + O(1)
// Searching for a value: O(n)